language: python
python: 2.7
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/Leeps-Lab/otree-core.git
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - otree test
env:
  - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
